
services:
  local-net-monit:
    restart: always
    network_mode: host
    build:
      context: ./
      dockerfile: ./cmd/localNetMonit/Dockerfile
    environment:
      - PORT=10001
    env_file:
      - .env
    volumes:
      - ./localNetMonit.json:/app/localNetMonit.json
      

  remote-port-check-server:
    network_mode: host
    restart: always
    build:
      context: .
      dockerfile: ./cmd/remotePortCheckServer/Dockerfile
    environment:
      - PORT=8081

