
services:
  local-net-monit:
    restart: always
    build:
      context: ./
      dockerfile: ./cmd/localNetMonit/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REMOTE_PORT_CHECKER_BASE_URL=http://remote-port-check-server:8081
      - MONITOR_PUBLIC_PORTS=true
      - MONITOR_LOCAL_PORTS=true
      - STATUS_PUBLIC_PORTS=true
      - STATUS_LOCAL_PORTS=false
      - PUBLIC_PORTS_FULL_CHECK_INTERVAL_MINUTES=120
      - LOCAL_PORTS_FULL_CHECK_INTERVAL_MINUTES=60
      - NB_PUBLIC_PORTS_TO_CHECK_PER_BATCH=20
      - SNAPSHOT_STORAGE_PATH=localNetMonit.json
      - WEB_SOCKET_URL=ws://localhost:8080/ws
    # env_file:
    #   - .env
    networks:
      - app-network

  remote-port-check-server:
    restart: always
    build:
      context: .
      dockerfile: ./cmd/remotePortCheckServer/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
